# Generated by Django 4.1.5 on 2023-01-05 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(help_text='В рублях', validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Стоимость')),
                ('odometer', models.IntegerField(help_text='В километрах', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('power', models.IntegerField(help_text='В лошадиных силах', validators=[django.core.validators.MinValueValidator(25)], verbose_name='Мощность')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет кузова')),
                ('number_plate', models.CharField(max_length=10, verbose_name='Гос.номер')),
            ],
        ),
    ]
