# Generated by Django 4.1.5 on 2023-01-05 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_manufacturer_model_vehicle_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='power',
        ),
        migrations.AddField(
            model_name='model',
            name='body_type',
            field=models.CharField(help_text='Тип кузова', max_length=70, null=True, unique=True, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='model',
            name='fuel_tank',
            field=models.DecimalField(decimal_places=2, help_text='Объем топливного бака', max_digits=5, null=True, verbose_name='Объем бака'),
        ),
        migrations.AddField(
            model_name='model',
            name='passengers',
            field=models.IntegerField(help_text='Количество пассажиров', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='model',
            name='power',
            field=models.IntegerField(help_text='В лошадиных силах', null=True, validators=[django.core.validators.MinValueValidator(25)], verbose_name='Мощность'),
        ),
    ]
