# Generated by Django 4.1.5 on 2023-01-08 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_remove_vehicle_power_model_body_type_model_fuel_tank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предприятия')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['cost'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Возраст')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный водитель')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.enterprise', verbose_name='Компания')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.enterprise', verbose_name='Компания'),
        ),
    ]
