# Generated by Django 4.1.5 on 2023-01-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_enterprise_alter_vehicle_options_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle',
            new_name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.driver', verbose_name='"Активный" водитель'),
        ),
    ]
