# Generated by Django 4.1.5 on 2023-01-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_alter_vehicle_active_driver_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='enterprises',
            new_name='enterprise',
        ),
    ]
