# Generated by Django 4.1.5 on 2023-01-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_alter_manager_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.enterprise', verbose_name='Компания'),
        ),
    ]
