# Generated by Django 4.1.5 on 2023-01-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_alter_vehicle_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='park.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='park.enterprise', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='park.enterprise', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='park.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='park.model', verbose_name='Модель'),
        ),
    ]
