# Generated by Django 4.1.5 on 2023-02-02 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_enterprise_timezone_vehicle_buy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='buy_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 5, 44, 10, 759351, tzinfo=datetime.timezone.utc), verbose_name='Дата и время покупки'),
        ),
    ]
