# Generated by Django 4.1.5 on 2023-02-02 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0012_alter_vehicle_buy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='buy_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время покупки'),
        ),
    ]
